"""Sound accents generated by ffmpeg itself (no licensing questions).

Each function returns a filter-chain string *without* the output label; add it with
`AudioGraph.chain(...)`.
"""

from __future__ import annotations

from vlogkit.timecode import fmt


def _place(at: float) -> str:
    ms = round(at * 1000)
    return f"aformat=channel_layouts=stereo,adelay={ms}|{ms}"


def whoosh(
    start: float, dur: float = 0.5, center_hz: float = 1400, gain: float = 0.9, seed: int = 42
) -> str:
    """Band-passed pink-noise swell; peaks at start + 0.76*dur."""
    rise = dur * 0.76
    return (
        f"anoisesrc=color=pink:d={fmt(dur)}:a=0.5:r=48000:seed={seed},"
        f"bandpass=f={fmt(center_hz)}:width_type=o:w=2.5,"
        f"afade=t=in:d={fmt(rise)}:curve=exp,afade=t=out:st={fmt(rise)}:d={fmt(dur - rise)},"
        f"volume={fmt(gain)},{_place(start)}"
    )


def impact(at: float, freq: float = 52, dur: float = 0.7, gain: float = 0.9) -> str:
    """Low sub 'boom' (lands a cut)."""
    return (
        f"sine=f={fmt(freq)}:d={fmt(dur)}:r=48000,afade=t=out:d={fmt(dur)}:curve=exp,"
        f"volume={fmt(gain)},{_place(at)}"
    )


def pop(at: float, freq: float = 1250, dur: float = 0.07, gain: float = 0.22) -> str:
    """Tiny click for caption / checklist pops."""
    return (
        f"sine=f={fmt(freq)}:d={fmt(dur)}:r=48000,afade=t=out:d={fmt(dur)}:curve=exp,"
        f"volume={fmt(gain)},{_place(at)}"
    )


def projector(start: float, dur: float, gain: float = 0.25, seed: int = 9) -> str:
    """Film projector rattle: band-limited noise chopped at 24 Hz (the shutter)."""
    return (
        f"anoisesrc=color=brown:d={fmt(dur)}:a=0.6:r=48000:seed={seed},"
        f"highpass=f=180,lowpass=f=3200,tremolo=f=24:d=0.85,"
        f"afade=t=in:d=0.15,afade=t=out:st={fmt(max(0.0, dur - 0.2))}:d=0.2,"
        f"volume={fmt(gain)},{_place(start)}"
    )


def hiss(start: float, dur: float, gain: float = 0.08, seed: int = 4) -> str:
    """TV static hiss (white noise, top end): under a "no signal" look."""
    return (
        f"anoisesrc=color=white:d={fmt(dur)}:a=0.5:r=48000:seed={seed},"
        f"highpass=f=1200,lowpass=f=9000,afade=t=in:d=0.08,"
        f"afade=t=out:st={fmt(max(0.0, dur - 0.12))}:d=0.12,volume={fmt(gain)},{_place(start)}"
    )


def rain(start: float, dur: float, gain: float = 0.18, seed: int = 6) -> str:
    """Steady rain (pink noise, band-limited): under a rain overlay."""
    return (
        f"anoisesrc=color=pink:d={fmt(dur)}:a=0.6:r=48000:seed={seed},"
        f"highpass=f=350,lowpass=f=7000,afade=t=in:d=0.3,"
        f"afade=t=out:st={fmt(max(0.0, dur - 0.35))}:d=0.35,volume={fmt(gain)},{_place(start)}"
    )


def guide_track(music, out, start: float, length: float, sr: int = 48000) -> None:
    """Stand-in groove WAV for an edit cut to a song that is not in the file (a tempo map,
    `analysis.music.grid`): it shows where the beats, bars and drops are, not how the song sounds.

    Per bar level: low = kick on the bar line + soft ticks, mid = kick on 1 and 3 + hats,
    high = kick on every beat + off-beat hats. A noise riser fills the bar before each drop and a
    crash lands on it. Times are song times; the file covers [start, start + length) and is exactly
    round(length * sr) samples long. Pure Python (no numpy).
    """
    import array
    import math
    import random
    import wave

    n = round(length * sr)
    buf = [0.0] * n
    rnd = random.Random(7)

    def add(at: float, dur: float, fn) -> None:
        i0 = round((at - start) * sr)
        for i in range(max(0, i0), min(n, i0 + round(dur * sr))):
            buf[i] += fn((i - i0) / sr, i)

    def kick(u, _):
        return (
            0.9
            * math.exp(-u * 18)
            * math.sin(2 * math.pi * (45 * u + 40 * (1 - math.exp(-u * 30)) / 30))
        )

    def hat(u, _):
        return 0.08 * math.exp(-u * 90) * (rnd.random() * 2 - 1)

    def tick(u, _):
        return 0.10 * math.exp(-u * 120) * math.sin(2 * math.pi * 2000 * u)

    half = music.beat_len / 2
    for bar in music.bars:
        if bar.end <= start or bar.start >= start + length:
            continue
        beats = [b for b in music.beats if bar.start - 1e-6 <= b < bar.end - 1e-6]
        for k, b in enumerate(beats):
            if bar.level == "high" or k == 0 or (bar.level == "mid" and k % 2 == 0):
                add(b, 0.25, kick)
            else:
                add(b, 0.03, tick)
            if bar.level != "low":
                add(b + half, 0.05, hat)
    rise = music.beat_len * 4

    def riser(u, _):
        return 0.12 * (u / rise) ** 2 * (rnd.random() * 2 - 1)

    def crash(u, _):
        return 0.14 * math.exp(-u * 5) * (rnd.random() * 2 - 1)

    for d in music.drops:
        add(d - rise, rise, riser)
        add(d, 0.8, crash)
    peak = max(1e-9, max(abs(v) for v in buf)) if buf else 1.0
    gain = 0.9 / peak if peak > 0.9 else 1.0
    pcm = array.array("h", (round(v * gain * 32000) for v in buf))
    with wave.open(str(out), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(sr)
        w.writeframes(pcm.tobytes())


def tape_rewind(
    input_idx: int,
    src_start: float,
    src_len: float,
    speed: float,
    at: float,
    length: float,
    gain: float = 0.9,
) -> str:
    """Tape-rewind squeal: a chunk of an input reversed and sped up (pitch rises with speed)."""
    return (
        f"[{input_idx}:a]atrim={fmt(src_start)}:{fmt(src_start + src_len)},asetpts=PTS-STARTPTS,"
        f"areverse,asetrate=48000*{fmt(speed)},aresample=48000,atrim=0:{fmt(length)},"
        f"highpass=f=250,lowpass=f=7000,volume={fmt(gain)},"
        f"afade=t=in:d=0.04,afade=t=out:st={fmt(length - 0.1)}:d=0.1,{_place(at)}"
    )
